apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-03-redis-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    lab: "lab-03"
    app-type: "cache"
    managed-by: "parent-app"
  annotations:
    # Sync wave: Deploy in wave 0 (databases first)
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.6.1
    chart: redis
    
    helm:
      parameters:
        - name: auth.enabled
          value: "false"
        - name: master.persistence.enabled
          value: "false"
        - name: replica.replicaCount
          value: "0"
        - name: master.resources.requests.memory
          value: "256Mi"
        - name: master.resources.requests.cpu
          value: "100m"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-03-cache
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
