apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-03-redis-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    lab: "lab-03"
    app-type: "cache"
    managed-by: "parent-app"
  annotations:
    # Sync wave: Deploy in wave 0 (databases first)
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  
  source:
    # Using simple Redis deployment from Git (workaround for Helm repo connectivity)
    repoURL: https://github.com/awaiskhan1/kubernetes.git
    targetRevision: HEAD
    path: lab-02-multiple-apps/redis-manifests
  
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-03-cache
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
